name: OpenSSF Scorecard

on:
  branch_protection_rule:
  schedule:
    - cron: "31 3 * * 2"
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  analysis:
    name: Scorecard analysis
    uses: AgentsKit-io/.github/.github/workflows/scorecard.yml@5a584290feaaa0a800a28d24583d16f15102bea1 # main
    permissions:
      contents: read
      id-token: write
      security-events: write
